### ISSUE TITLE
Failed to build in windows 11

### ISSUE THREAD

**Issue by faridreaming** [tfkhdyt/pomodoro#1]
![image](https://github.com/tfkhdyt/pomodoro/assets/97384053/beb38f34-ea00-4189-be79-2da1b90808d4)

kok error ya mas

**Comment by tfkhdyt** [comment]
cobain pre-build binary-nya aja

https://github.com/tfkhdyt/pomodoro/releases/tag/v0.7.5

**Comment by faridreaming** [comment]
oke mas, thanks
